- docs/DeveloperGuide.md
- docs/Gemfile
- docs/_config.yml
1. Update metadata in related files in `/docs`
2. Update User stories and Non-Functional Requirements sections in the Developer Guide for v1.1
Close #4
> Update User stories and Non-Functional Requirements in the Developer Guide for v1.1

- docs/DeveloperGuide.md
1. Update Product Scope and Glossary of Developer Guide for V1.1
2. Closes #6
> Update Product Scope and Glossary of Developer Guide for V1.1

- docs/UserGuide.md
1. Removed remaining references to 'Addressbook'
2. Modified 'Find' command
2.1 Initially was going to edit it as Abdul had suggested, but upon rereading the 'notes about command format' section I think this version follows those guidelines better
> More updates to UserGuide.md

- docs/DeveloperGuide.md
> Add "add person" use case

- docs/DeveloperGuide.md
PR update relating to issue #10
> DeveloperGuide.md updated with 'Delete tag from person' use-case

- docs/DeveloperGuide.md
1. Make minor changes to DG to fix formatting errors.
> Edit DeveloperGuide.md to fix formatting errors

- src/main/resources/view/DarkTheme.css
- src/main/resources/view/MainWindow.fxml
1. PR related to #36
2. Added JavaFX tab-pane as shown in the image below.
> Add tab-pane into GUI

- src/main/resources/view/MainWindow.fxml
> Fix the white blank area in full screen GUI

- src/test/java/seedu/address/logic/commands/AddNoteCommandTest.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/parser/AddNoteCommandParserTest.java
- src/test/java/seedu/address/model/note/NoteTest.java
> Add testing methods for AddNoteCommand

- src/main/java/seedu/address/commons/core/Messages.java
- src/main/java/seedu/address/logic/commands/DeleteNoteCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/DeleteNoteCommandParser.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/test/java/seedu/address/logic/commands/DeleteNoteCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/DeleteNoteCommandParserTest.java
- src/test/java/seedu/address/logic/parser/ParserUtilTest.java
- src/test/java/seedu/address/testutil/TypicalIndexes.java
1. Implements the `note-del` feature
2. Closes #35 
3. Contains related test methods
> Implement the note-del feature

- src/main/java/seedu/address/ui/MainWindow.java
- src/main/java/seedu/address/ui/StrategyPanel.java
- src/main/resources/view/MainWindow.fxml
- src/main/resources/view/StrategyPanel.fxml
1. Closes #52
2. Currently issue: you can drag the object out of the boundary 
So basically just 3 circles you can drag and move in the strategy panel
> Implement drag and move features in StrategyPanel

- src/main/java/seedu/address/logic/commands/AddTagCommand.java
- src/main/java/seedu/address/logic/commands/DeleteTagCommand.java
- src/main/java/seedu/address/logic/parser/AddTagCommandParser.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/DeleteTagCommandParser.java
1. PR related to #42 
2. Implemented tag-add and tag-del feature
3. Related unit tests to be added soon
> Implement tag-add and tag-del feature

- src/main/java/seedu/address/commons/core/Messages.java
- src/main/java/seedu/address/logic/commands/AddTaskCommand.java
- src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
- src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/logic/parser/DeleteTaskCommandParser.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/model/task/EndTime.java
- src/main/java/seedu/address/model/task/StartTime.java
1. PR related to #43 
2. Implemented add-task and delete-task feature 
3.  Related unit tests to be added soon
> Implement Add-task and delete-task feature

- src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/commands/DeleteTaskCommandTest.java
- src/test/java/seedu/address/logic/parser/AddTaskCommandParserTest.java
- src/test/java/seedu/address/logic/parser/DeleteTaskCommandParserTest.java
- src/test/java/seedu/address/testutil/TypicalIndexes.java
- src/test/java/seedu/address/testutil/TypicalTasks.java
PR for issue #64 
Added tests for:
- AddTaskCommand
- DeleteTaskCommand
- AddTaskCommandParser
- DeleteTaskCommandParser
> Add tests for add-task and delete-task commands

- src/main/java/seedu/address/logic/commands/ClearTaskCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/ClearTaskCommandParser.java
- src/test/java/seedu/address/logic/commands/ClearTaskCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/ClearTaskCommandParserTest.java
- src/test/java/seedu/address/testutil/TypicalTasks.java
1. Implements `clear-t` command
2. Includes relevant test classes
3. Closes #77
> Implement clear tasks function

- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/logic/commands/AddTagCommand.java
- src/main/java/seedu/address/logic/commands/AddTaskCommand.java
- src/main/java/seedu/address/logic/commands/ClearCommand.java
- src/main/java/seedu/address/logic/commands/DeleteCommand.java
- src/main/java/seedu/address/logic/commands/DeleteTagCommand.java
- src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/commands/FindCommand.java
- src/main/java/seedu/address/logic/commands/ListCommand.java
- src/test/java/seedu/address/logic/LogicManagerTest.java
1. PR related to #87
2. Minor changes to command format
> Update command format to match UG

- docs/UserGuide.md
1. PR linked to #86 
2. Fix header formatting issues
> Fix minor issue in UG

- src/main/java/seedu/address/commons/core/Messages.java
- src/main/java/seedu/address/logic/Logic.java
- src/main/java/seedu/address/logic/LogicManager.java
- src/main/java/seedu/address/logic/commands/strategy/AddPlayerCommand.java
- src/main/java/seedu/address/logic/commands/strategy/DeletePlayerCommand.java
- src/main/java/seedu/address/logic/commands/strategy/MovePlayerCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/logic/parser/strategy/MovePlayerCommandParser.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/ReadOnlyStrategyBoard.java
- src/main/java/seedu/address/model/StrategyBoard.java
- src/main/java/seedu/address/model/strategy/Player.java
- src/main/java/seedu/address/model/strategy/UniquePlayerList.java
- src/main/java/seedu/address/ui/StrategyPanel.java
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
Close #117 
Usage: `move PLAYER_NAME x/X_COORDINATE y/Y_COORDINATE`
Possible issue: 
- maybe a upper bound is needed otherwise the player will be moved outside of the view
- no testing methods
- need update UG & DG
> Implement move player feature

- src/main/java/seedu/address/commons/core/Messages.java
- src/main/java/seedu/address/logic/commands/SortStrengthCommand.java
- src/main/java/seedu/address/logic/commands/SortWeaknessCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/test/java/seedu/address/logic/commands/SortStrengthCommandTest.java
- src/test/java/seedu/address/logic/commands/SortWeaknessCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/testutil/TypicalPersons.java
1. Closes #102 
2. Implements the `sort-strength` and `sort-weakness` commands
3. Includes relevant test cases
> Implement sort-strength and sort-weakness features

- docs/DeveloperGuide.md
- docs/UserGuide.md
- docs/team/aalghrairy.md
1. Related to #71 
2. Closes #103 and #111 
3. Adds feature definitions for `sort-strength` and `sort-weakness` commands in User Guide
4. Include rational for Strength and Weakness functions in Q&A section of User Guide
5. Adds use cases and a user story to Developer Guide
6. Adds additional fields to individual PPP
> Individual Documentation update for v1.3b

- src/main/java/seedu/address/logic/commands/DeleteTagFromTaskCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/DeleteTagFromTaskCommandParser.java
Related to #128 
1) Implemented **delete tags from tasks** functionality
> Feature: Delete tags from tasks

- docs/UserGuide.md
> Update UG with sort task by date details

- docs/DeveloperGuide.md
- docs/UserGuide.md
1. PR related to #131
2. Added the following use cases into DG (find-t, get-person)
3. Added the following commands into UG (get-person)
4. Update the remaining parts of the command summary in UG
5. Minor documentation amendments to `delete task` use case and `move-player` feature in UG
6. Removed `clear-player` feature from UG
> Update UGDG with assigned features

- src/test/java/seedu/address/logic/commands/SortTaskByDateCommandTest.java
- src/test/java/seedu/address/testutil/TypicalTasks.java
> Implemented test cases for sort tasks by date

- src/main/java/seedu/address/logic/commands/strategy/AddPlayerCommand.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/logic/parser/strategy/AddPlayerCommandParser.java
- src/main/java/seedu/address/model/strategy/Player.java
- Add new constraints to the player name and slightly change the parsing workflow of `AddPlayerCommand`.
- Now the character "/" is not allowed to appear in the player name.
Close #204
> Fix the special character in player name bug

- docs/UserGuide.md
- Add player name constraints.
- "`PLAYER_NAME` name" in the screenshot below is a typo and already be fixed
Close #205 #189
> Update the UG to reflect the player name constraints

- docs/UserGuide.md
- src/main/java/seedu/address/logic/parser/exceptions/ParseException.java
1. Add clarifications for note related functions in User Guide
> Fix note related documentation bugs v1.4

- docs/team/simjunheng.md
> Update personal PPP

- src/main/java/seedu/address/model/note/Note.java
- src/test/java/seedu/address/model/note/NoteTest.java
1. Closes #166 
2. Fixes issue of note equals not being case sensitive
3. Add additional test cases for note class
> Fix case insensitive note bug

- src/main/java/seedu/address/logic/commands/SortTaskByDateCommand.java
> Fix sort-date wiping all taskbook data

- src/main/java/seedu/address/logic/parser/DeleteTagFromTaskCommandParser.java
- src/test/java/seedu/address/logic/commands/DeleteTagFromTaskCommandTest.java
- src/test/java/seedu/address/logic/parser/DeleteTagFromTaskCommandParserTest.java
> Implemented test cases for delete tasks from tag

- docs/DeveloperGuide.md
> Update DG with sort tasks by date command

- docs/UserGuide.md
1. PR related to #213 
2. Added the purpose of the guide, the target audience and included clear and complete information about how to use the guide.
> Add "About the User Guide" section into UG

- src/main/java/seedu/address/logic/parser/person/AddPersonTagCommandParser.java
- src/main/java/seedu/address/logic/parser/person/DeletePersonTagCommandParser.java
- src/main/java/seedu/address/logic/parser/task/AddTaskTagCommandParser.java
- src/main/java/seedu/address/logic/parser/task/DeleteTaskTagCommandParser.java
- src/test/java/seedu/address/testutil/TestImageCreator.java
Related to #113 
Add tag-editing commands should now display an error when the first parameter is not an integer index
> Bugfix for #113

- src/test/java/seedu/address/logic/commands/strategy/ExportCommandTest.java
1. PR regarding testcases for `Export` to increase coverage #138
> export-command testcase

- src/main/java/seedu/address/logic/commands/task/AddTaskCommand.java
- src/main/java/seedu/address/logic/commands/task/EditTaskCommand.java
- src/main/java/seedu/address/model/task/Task.java
- src/test/java/seedu/address/logic/commands/task/EditTaskCommandTest.java
1. PR regarding issue #158
2. Added time validity and person-time compatibility checking into `edit-t`
3. Added/edited test cases for the new checks
> add-task bug fix

- docs/UserGuide.md
Related to #213.
Added my assigned signposting section (features).
> Add signposting for the features section

- docs/UserGuide.md
> Add signposting to command summary section in UG

- src/main/java/seedu/address/model/strategy/Player.java
- src/main/java/seedu/address/ui/StrategyPanel.java
PR related to #200 
- Relative positions with width `1000` and height `600`
- No need to revert y-axis
- Modify the original position
> Update move player feature to support relative positions

- src/main/java/seedu/address/ui/StrategyPanel.java
PR related to #182 
Now the move position is more accurate 
Once this is merged, I will update the constraints of `move` and also update UG
> Fix the position of move player

- src/main/java/seedu/address/logic/commands/strategy/AddPlayerCommand.java
- src/main/java/seedu/address/model/strategy/Player.java
> Revert the player name limit to 50

- docs/UserGuide.md
1. PR relating to #213 and #110
> Edits made to the UG

- src/test/java/seedu/address/logic/commands/strategy/AddPlayerCommandTest.java
- src/test/java/seedu/address/logic/commands/strategy/DeletePlayerCommandTest.java
- src/test/java/seedu/address/logic/commands/strategy/MovePlayerCommandTest.java
- src/test/java/seedu/address/model/strategy/PlayerTest.java
> Add testing cases for strategy board related classes

- docs/AboutUs.md
- docs/team/prgj.md
> Updates to PPP
